[package]
name = "mac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
cbc-mac = "0.1.1"
aes = "0.8.2"
generic-array = "0.14.6"
hex-literal = "0.3.4"
